baseURL = 'https://meirkriheli.com'
languageCode = 'he'
title = 'Meir Kriheli'
theme = 'ananke'
defaultContentLanguage = 'he'
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
Paginate = 9
disqusShortname = 'meirkriheli'

[permalinks]
  posts = '/:year/:month/:slug/'

[languages]
  [languages.he]
    languageDirection = "rtl"
    weight = 1
    contentDir = "content/he"
    languageName = "Hebrew"
    [languages.he.menu]
      [[languages.he.menu.main]]
      name = 'תגים'
      pageref  = '/tags'
      weight = 1
     
  [languages.en]
    weight = 2
    contentDir = "content/en"
    languageName = "English"
    [languages.en.menu]
      [[languages.en.menu.main]]
      name = 'Tags'
      pageref = '/tags'
      weight = 1

[params]
  body_classes = "alef bg-solarized"
  custom_css = ["meir.css", "jquery.bxslider.css"]
  text_color = "fg-solarized"
  post_content_classes = "alef tj"
  background_color_class = "bg-alt-background"
  recent_posts_number = 5


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/mkriheli"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/MeirKriheli"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/meirkriheli"


[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "feed"

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["rss"]


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
